# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-03-27 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.CharField(max_length=500)),
                ('album_logo', models.FileField(upload_to='')),
                ('album_intro', models.CharField(max_length=1000)),
                ('album_release_date', models.CharField(max_length=30)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('artist', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer_name', models.CharField(max_length=50)),
                ('singer_intro', models.CharField(blank=True, max_length=1000)),
                ('singer_avatar', models.FileField(blank=True, upload_to='')),
                ('is_favorite', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=100)),
                ('song_lyric', models.CharField(blank=True, max_length=1000)),
                ('audio_file', models.FileField(upload_to='')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Category')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Singer')),
            ],
        ),
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=500)),
                ('song_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Category'),
        ),
        migrations.AddField(
            model_name='album',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Singer'),
        ),
    ]
