# Generated by Django 2.0.7 on 2019-12-23 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='music.Category'),
        ),
        migrations.AlterField(
            model_name='album',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='music.Singer'),
        ),
        migrations.AlterField(
            model_name='singer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='music.Category'),
        ),
        migrations.AlterField(
            model_name='song',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='music.Category'),
        ),
        migrations.AlterField(
            model_name='song',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='music.Singer'),
        ),
    ]
