# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-03-27 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='category',
        ),
        migrations.RemoveField(
            model_name='song',
            name='singer',
        ),
    ]
